### ISSUE TITLE
Request for different key name in manifest.json

### ISSUE THREAD

**Issue by shimwell** [ukaea/parallel-preprocessor#12]
The manifest.json looks for the tag ```filename``` but I was wondering if this could be changed to ```stp_filename```

No worries if it is better to keep it as filename, just thought I would ask

**Comment by qingfengxia** [comment]
yes, it is possible. will do soon.  thank you

**Comment by makeclean** [comment]
this should likely stay as filename, what if one gave it an igs file? or a brep file?

**Comment by qingfengxia** [comment]
For our loyalty tester, I added this feature,   it will search a key containing "filename" so  "stp_filename" is working now

**Comment by shimwell** [comment]
I just have a manifest which references a few different file types, so I have and entry in the manifest file for stl_filename, stp_filename and a few others. Will this containing filename get confused if it picks up a few which match that criteria?

**Comment by shimwell** [comment]
Perhaps another approach is to have a default dictionary key of filename but allow the user to overwrite this and specify the dictionary key they would like to use in the manifest file. Or perhaps this is unnecessarily complex?

**Comment by makeclean** [comment]
@qingfengxia it would be good if you could reference the issue in the PR that you make, im trying to find any changes you've made to figure out the answer to @Shimwell's question, but seeing as I cant find an open PR that would be associated with it, I'm at a loss. Note you can use the # symbol and then a list appears of open issues and pr's

**Comment by shimwell** [comment]
Sorry for causing perhaps more trouble than this issues is worth.
