### ISSUE TITLE
command line usage with args -o not working

### ISSUE THREAD

**Issue by shimwell** [ukaea/parallel-preprocessor#13]
When running ```/usr/bin/python /usr/bin/geomPipeline.py manifest.json -o ppp.brep```

I think I am using the geomPipeline correctly according to the --help instructurings I get a RuntimeError 

![Screenshot from 2020-10-14 09-32-28](https://user-images.githubusercontent.com/8583900/95964214-79bab480-0e00-11eb-9021-b92b1c1152b4.png)

![Screenshot from 2020-10-14 09-32-53](https://user-images.githubusercontent.com/8583900/95964184-6f98b600-0e00-11eb-9e0b-0386363f00c4.png)

**Comment by qingfengxia** [comment]
confirmed,  further I will add a command line  test this -o option

**Comment by qingfengxia** [comment]
This should be fixed,           I added "nargs =1" wrongly  so   args.outputFile is a list instead of string.
