### ISSUE TITLE
errors when running geompipline

### ISSUE THREAD

**Issue by shimwell** [ukaea/parallel-preprocessor#2]
When trying to use the geomPipeline.py in ubuntu 18.04 Conda env I get an error and was wondering 

![Screenshot from 2020-10-07 14-58-36](https://user-images.githubusercontent.com/8583900/95340945-abd29080-08ad-11eb-9391-96606912b91c.png)

I have tried installing additional software ```sudo apt-get install libstdc++6``` but this has not helped

Here are the commands I used to install and run the PPP

```
sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
sudo apt update
sudo install -y freecad
sudo apt-get install -y libtbb2 libocct-foundation-7.3  libocct-data-exchange-7.3  libocct-modeling-data-7.3 libocct-modeling-algorithms-7.3  libocct-ocaf-7.3
wget https://github.com/ukaea/parallel-preprocessor/releases/download/dev/parallel-preprocessor-0.3-dev_ubuntu-20.04.deb
sudo dpkg -i parallel-preprocessor-0.3-dev_ubuntu-20.04.deb 
geomPipeline.py config.json
/home/jshim/anaconda3/bin/python /usr/bin/geomPipeline.py config.json
```

**Comment by qingfengxia** [comment]
the package you downloaded is for ubuntu 20.04,  there is another one  ubuntu 18.04
https://github.com/ukaea/parallel-preprocessor/releases/download/dev/parallel-preprocessor-0.3-dev_ubuntu-18.04.deb

Currently C-extension ppp is optionally,   it means you should be able to use conda python to run geomPipeline.py

**Comment by qingfengxia** [comment]
but there is still some other issues, some unit test failed, I had made some big refactoring recently, move files around.

**Comment by shimwell** [comment]
Ah sorry for my silly mistake, retrying with version for 18.04 :-)
