### ISSUE TITLE
Shape hash or uniqueId algorithm has problem

### ISSUE THREAD

**Issue by qingfengxia** [ukaea/parallel-preprocessor#20]
ukaea/openmc_workshop  task10

for small value  like centerOfMess.X = 0.014 (before write brep) vs  0.012 (after write out brep in occ_faceter)   has diff value, 

No material found for ID: 4710765210376886256
with volume: 1.26734e+08, CentreOfMass: 0.0145901, -9.97406e-15, 268.845

    "material": "copper",
    "name": "divertor.stp",
    "property": {
        "area": 2300829.253375523,
        "centerOfMass": [
            0.012942664269858002,
            -1.6442619387761406e-14,
            268.84456044917755
        ],
        "volume": 126733088.77402382
    },
    "uniqueId": 4710765210367973360

No material found for ID: 13934137247231662064
with volume: 1.26734e+08, CentreOfMass: 0.0145901, -1.254e-14, -268.845

    "material": "copper",
    "name": "divertor.stp",
    "property": {
        "area": 2300829.253375234,
        "centerOfMass": [
            0.012942664144260964,
            -1.43356289324801e-14,
            -268.84456044879204
        ],
        "volume": 126733088.77435534
    },
    "uniqueId": 13934137247222749168

**Comment by qingfengxia** [comment]
one solution, is turn off unique ID check in occ_faceter,  it is now known brep write-out and readin sequence is fixed.

**Comment by makeclean** [comment]
If its guarenteed, then lets do it!

**Comment by qingfengxia** [comment]
if a value is less than 1, then make it zero, before hashing,  to  by pass this issue20. 

while, run into error:         no matter tolerance size of  occ_faceter

qxia@K0244:/mnt/windata/MyData/openmc_workshop/tasks/task_10$ make_watertight dagmc_notwatertight.h5m -o dagmc.h5m
Loading input file...
  faceting tolerance=0.0001 cm
  absolute tolerance=1e-06 cm
finished in get_geom_size_before_sealing
Getting entity count before sealing...
  input faceted geometry contains 13 volumes, 65 surfaces, 187 curves, and 418185 triangles
Finding degenerate triangles... 
Modifying faceted curve representation and removing small curves...
Identifying coincident curves to be merged...
Zipping loops and removing small surfaces whose curves were all merged as pairs...
SME_RESABS_TOL = 1e-06 facet_tol = 0.0001
MOAB ERROR: --------------------- Error Message ------------------------------------
MOAB ERROR: too many endpt_sets!
MOAB ERROR: seal_loop() line 793 in MakeWatertight.cpp
failed to zip: surface 1: failed to seal a loop
MOAB ERROR: --------------------- Error Message ------------------------------------
MOAB ERROR: Failed to get the curve to surface entity tag handle!
MOAB ERROR: check_edge_sense_tags() line 1220 in src/GeomTopoTool.cpp
MOAB ERROR: --------------------- Error Message ------------------------------------
MOAB ERROR: Failed to check the curve to surface sense tag handles!
MOAB ERROR: get_senses() line 1071 in src/GeomTopoTool.cpp
MOAB ERROR: --------------------- Error Message ------------------------------------
MOAB ERROR: could not get the surfs/senses of the curve to delete!
MOAB ERROR: combine_merged_curve_senses() line 1832 in Gen.cpp
MOAB ERROR: --------------------- Error Message ------------------------------------
MOAB ERROR: could not combine the merged curve sets!
MOAB ERROR: prepare_surfaces() line 1089 in MakeWatertight.cpp

**Comment by makeclean** [comment]
that error isnt due to PPP its due to occ_faceter, im working on it :)

**Comment by qingfengxia** [comment]
Thank you Andy, I assumed  occ_faceter output has already water-tight.  cp  dagmic_not_watertight.h5m   damgc.h5m
then run the example py of task10
```
Implicit Complement assumed to be Vacuum
 ERROR: No material li4sio4 found for volume (cell) 13
```

 I guess I have not installed the material lib, or  material name is not correct. 
I only install  "tendl-2019-hdf5" it seems for Atom not for   compound  like Li4SiO4

**Comment by shimwell** [comment]
That li4sio4 is the material name in this case. Nothing to do with the nuclear data
