### ISSUE TITLE
missing file pppStartPipeline

### ISSUE THREAD

**Issue by shimwell** [ukaea/parallel-preprocessor#8]
This might be me making the error again but wanted to mention that I'm getting this error, Looks like PPP can't find the pppStartPipeline file and it appears to not have installed with the others

![Screenshot from 2020-10-12 20-41-25](https://user-images.githubusercontent.com/8583900/95784588-057ef480-0ccc-11eb-9ad0-8f07880d41a5.png)

![Screenshot from 2020-10-12 20-46-39](https://user-images.githubusercontent.com/8583900/95784626-14fe3d80-0ccc-11eb-936d-e310c856b5c0.png)

**Comment by qingfengxia** [comment]
thank you, remember some thing is not done correctly.  sorry about that. will fix it  soon

**Comment by qingfengxia** [comment]
I will fix it tomorrow morning. I had other code change, breaking the ci for v18.04

**Comment by qingfengxia** [comment]
Today's fix should have fixed this bug,  forget to install() in cmakelists.txt

**Comment by shimwell** [comment]
Thanks for fixing #8 , looking forward to trying the code.

Will there be another release or daily build generated automatically so I can try out the new improved code

https://github.com/ukaea/parallel-preprocessor/releases
